"""Type stubs for splayed."""
from typing import Optional, List, Iterator, Dict, Any
import pyarrow as pa

class PartitionScheme:
    NONE: str
    YEAR: str
    MONTH: str
    DAY: str

class TableBatchReader:
    def __iter__(self) -> Iterator[pa.RecordBatch]: ...
    def __next__(self) -> pa.RecordBatch: ...
    def next(self) -> Optional[pa.RecordBatch]: ...
    def read_all(self) -> pa.Table: ...
    def close(self) -> None: ...

class TableReader:
    @classmethod
    def open(cls, path: str, max_parallelism: Optional[int] = None) -> "TableReader": ...
    def read(
        self,
        symbols: Optional[List[str]] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        columns: Optional[List[str]] = None,
        limit: Optional[int] = None,
        batch_size: Optional[int] = None,
    ) -> TableBatchReader: ...
    def read_all(
        self,
        symbols: Optional[List[str]] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        columns: Optional[List[str]] = None,
        limit: Optional[int] = None,
    ) -> pa.Table: ...
    def schema(self) -> pa.Schema: ...
    def statistics(self) -> Dict[str, Any]: ...
    def metadata(self) -> Dict[str, Any]: ...
    def path(self) -> str: ...
    def scheme(self) -> str: ...
    def close(self) -> None: ...

class TableWriter:
    @classmethod
    def create(
        cls,
        path: str,
        schema: pa.Schema,
        scheme: str = "none",
        initial_partition: Optional[str] = None,
        max_parallelism: Optional[int] = None,
    ) -> "TableWriter": ...
    @classmethod
    def init(
        cls,
        path: str,
        batch: pa.RecordBatch,
        scheme: str = "none",
        max_parallelism: Optional[int] = None,
    ) -> "TableWriter": ...
    @classmethod
    def open(cls, path: str, max_parallelism: Optional[int] = None) -> "TableWriter": ...
    def write(self, data: Any) -> None: ...
    def update(self, data: Any) -> None: ...
    def delete_partition(self, partition_name: str) -> None: ...
    def init_field(self, field_name: str, data_type: str, opts: Optional[Any] = None) -> None: ...
    def delete_field(self, name: str) -> None: ...
    def rename_field(self, name: str, new_name: str) -> None: ...
    def cast_field(self, name: str, target_type: str) -> None: ...
    def compress_field(self, name: str) -> None: ...
    def decompress_field(self, name: str) -> None: ...
    def fix(self) -> None: ...
    def as_reader(self) -> TableReader: ...
    def schema(self) -> pa.Schema: ...
    def statistics(self) -> Dict[str, Any]: ...
    def metadata(self) -> Dict[str, Any]: ...
    def path(self) -> str: ...
    def scheme(self) -> str: ...
    def close(self) -> None: ...
    def remove(self) -> None: ...
