from __future__ import annotations

import os
from typing import Any, Sequence, Optional, Union
from pathlib import Path

class PartitionScheme:
    NONE: Any
    DAY: Any
    MONTH: Any
    YEAR: Any

class TableReader:
    @classmethod
    def open(cls, path: str, max_parallelism: Optional[int] = None) -> TableReader: ...
    def schema(self) -> Any: ...
    def statistics(self) -> dict[str, Any]: ...
    def metadata(self) -> dict[str, Any]: ...
    def read(
        self,
        symbols: Optional[Sequence[str]] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        columns: Optional[Sequence[str]] = None,
        limit: Optional[int] = None,
        batch_size: Optional[int] = None,
    ) -> TableBatchReader: ...
    def read_all(
        self,
        symbols: Optional[Sequence[str]] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        columns: Optional[Sequence[str]] = None,
        limit: Optional[int] = None,
        max_parallelism: Optional[int] = None,
    ) -> Any: ...
    def read_batches(
        self,
        symbols: Optional[Sequence[str]] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        columns: Optional[Sequence[str]] = None,
        limit: Optional[int] = None,
        max_parallelism: Optional[int] = None,
    ) -> list[Any]: ...
    def close(self) -> None: ...

class TableWriter:
    @classmethod
    def create(
        cls,
        path: str,
        schema: Any,
        scheme: str = "none",
        initial_partition: Optional[str] = None,
        max_parallelism: Optional[int] = None,
    ) -> TableWriter: ...
    @classmethod
    def init(
        cls,
        path: str,
        batch: Any,
        scheme: str = "none",
        max_parallelism: Optional[int] = None,
    ) -> TableWriter: ...
    @classmethod
    def open(cls, path: str, max_parallelism: Optional[int] = None) -> TableWriter: ...
    def write(self, batch: Any) -> None: ...
    def update(self, batch: Any) -> None: ...
    def delete_partition(self, partition_name: str) -> None: ...
    def init_field(self, field_name: str, data_type: str) -> None: ...
    def delete_field(self, field_name: str) -> None: ...
    def rename_field(self, field_name: str, new_name: str) -> None: ...
    def cast_field(self, field_name: str, target_type: str) -> None: ...
    def compress_field(self, field_name: str) -> None: ...
    def decompress_field(self, field_name: str) -> None: ...
    def fix(self) -> None: ...
    def schema(self) -> Any: ...
    def statistics(self) -> dict[str, Any]: ...
    def metadata(self) -> dict[str, Any]: ...
    def as_reader(self) -> TableReader: ...
    def close(self) -> None: ...
    def remove(self) -> None: ...

class TableBatchReader:
    def __iter__(self) -> TableBatchReader: ...
    def __next__(self) -> Any: ...
    def read_all(self) -> Any: ...

def scan_splayed(
    path: str | Path,
    *,
    allow_filter: bool = True,
    batch_size: int | None = None,
) -> Any: ...

def sink_splayed(
    data: Any,
    path: str | Path,
    *,
    scheme: str = "none",
    max_parallelism: int | None = None,
) -> None: ...
